### ISSUE TITLE
Admin panel theme not working correctly

### ISSUE THREAD

**Issue by txdv** [d4fseeker/PsychoStats-extended#11]
When the temporary directory does not exist it will create a temporary directory in tmp, but the admin panel theme won't work correctly.

**Comment by d4fseeker** [comment]
As of commit 0e32cf8b23a5e7a9751f PsychostatsX does no longer use the /tmp/ folder for caching but a folder within it's own file structure. The admin theme is not cached by the template engine, thus should never show the described effect.
Please give reproduction steps, could not reproduce in Ubuntu LTS

**Comment by txdv** [comment]
Install it with the temporary directory select to /home/user/tmp, delete the entire directory, now ps will save it in /tmp

**Comment by d4fseeker** [comment]
Issue is being analyzed

**Comment by d4fseeker** [comment]
Issue Importance: high

Seems to be a regression in PsychoX
