### ISSUE TITLE
Maxmind error when installing PsychoStats 3.2.2b on Debian 5.0

### ISSUE THREAD

**Issue by ps-joe** [d4fseeker/PsychoStats-extended#13]
I tried several times to install PsychoStats 3.2.2b on my Debian 5.0 server. Installing official Psychostats 3.2 worked without any problems. Then I deleted the whole files of 3.2 and installed a fresh and new PsychoStats extended 3.2.2b.
## Everything went fine until I pressed "Initialize Database"-button, then following error came up:

Initialization Result
There were errors initializing the database. You database is NOT currently setup properly! The errors below must be resolved before continuing. 
## Unable to read Maxmind GeoIP database for installation!

PsychoStats 3.2.2b is a full package and not only an update package which depends on prior installation of PsychoStats 3.2, right?

Would be very nice if somebody with more experience in PsychoStats coding could look into it. Thanks.

Greetz
psjoe

System specs:
Debian 5.0 --> with latest updates
Apache 2.2.9
MySQL 5.0.51
PHP 5.2.6

**Comment by ps-joe** [comment]
GitHub screwed up the error message formatting a bit. Please see error message in better formatting below:

Initialization Result
There were errors initializing the database. You database is NOT currently setup properly! The errors below must be resolved before continuing. 

Unable to read Maxmind GeoIP database for installation!

**Comment by ps-joe** [comment]
PROBLEM SOLVED!

Problem was a that the maxmind.sql file was owned by root. This is very strange as all other files and directories were owned by www-data and I never touched maxmind.sql???

Very strange... but solved

**Comment by d4fseeker** [comment]
Hm, could you please re-upload it again (or unpack it) into another folder and check if it's again owned by root?

**Comment by ps-joe** [comment]
Hi d4fseeker,

I extracted the archive once more and everything was fine. I don't know why this happened, but I am completely sure I never touched maxmind.sql before.

I don't know if this might be an occasional happening bug of PsychoStats or if it was because of my webserver, sorry.

**Comment by d4fseeker** [comment]
Usually you shouldnt have files owned by another user, so I'll close the issue
[CLOSED]
